import { type Metadata } from 'next';
import PageHero from '@/components/layout/PageHero';
import FlangeTypesGuideClient from './FlangeTypesGuideClient';

export const metadata: Metadata = {
  title: 'The Complete Flange Types Guide | 15 Types Explained',
  description:
    'Comprehensive guide to 15 flange types including weld neck, slip-on, blind, threaded, socket weld, lap joint, and more. Learn characteristics, applications, standards, and selection criteria.',
  keywords: [
    'flange types',
    'weld neck flange',
    'slip-on flange',
    'blind flange',
    'threaded flange',
    'socket weld flange',
    'lap joint flange',
    'reducing flange',
    'flange guide',
    'ASME B16.5',
    'flange selection',
    'flange applications',
  ],
  openGraph: {
    title: 'The Complete Flange Types Guide: 15 Types Explained',
    description:
      'Master all 15 flange types with detailed specifications, applications, and selection criteria.',
    type: 'article',
    url: 'https://www.apiflange.com/resources/flange-types-guide',
  },
};

interface TOCItem {
  id: string;
  title: string;
  level: number;
}

interface FlangeType {
  id: string;
  name: string;
  definition: string;
  characteristics: string[];
  pros: string[];
  cons: string[];
  applications: string[];
  standards: string[];
  faceOptions: string[];
}

const flangeTypes: FlangeType[] = [
  {
    id: 'weld-neck',
    name: 'Weld Neck Flange',
    definition:
      'A weld neck flange features a long tapered hub that is welded to the pipe. The tapered design provides stress relief and distributes loads gradually, reducing stress concentration at the weld. This is the most commonly used flange type in high-pressure and high-temperature applications.',
    characteristics: [
      'Long tapered hub with gradual transition to pipe',
      'Excellent stress distribution properties',
      'Higher cost than slip-on due to machining and material',
      'Requires full penetration weld for structural integrity',
      'Bore matches pipe ID (butt weld compatible)',
      'Available in standard and long weld neck (LWN) configurations',
    ],
    pros: [
      'Superior stress distribution and reduced fatigue loading',
      'Best for high-temperature and high-pressure services',
      'Excellent corrosion resistance at weld area due to gradual transition',
      'Lower vibration and deflection',
      'Most common type - proven track record in critical applications',
      'Better for thick-wall piping systems',
    ],
    cons: [
      'Higher cost compared to slip-on flanges',
      'Requires skilled welders for proper installation',
      'More complex machining increases lead times',
      'Rigid connection reduces flexibility for misalignment',
      'Difficult to repair or remove without cutting pipe',
    ],
    applications: [
      'High-pressure steam and hot water systems',
      'Petrochemical and chemical processing plants',
      'Power generation (steam, combined cycle, geothermal)',
      'Oil and gas pipelines',
      'Cryogenic services (LF2 material)',
      'High-temperature thermal applications',
      'Severe service and critical pressure systems',
    ],
    standards: [
      'ASME B16.5 (Classes 150-2500)',
      'ASME B16.47 Series A & B (large diameter)',
      'API 6A (wellhead equipment)',
      'EN 1092-1 (European standard)',
    ],
    faceOptions: ['Raised Face (RF)', 'Ring Joint (RTJ)', 'Flat Face (FF)', 'Tongue & Groove (T&G)'],
  },
  {
    id: 'slip-on',
    name: 'Slip-On Flange',
    definition:
      'A slip-on flange slides over the pipe and is secured with fillet welds on both the inner and outer diameters. The flange bore is slightly larger than the pipe OD, allowing the pipe to slide through. This type is simpler to manufacture and install than weld neck flanges.',
    characteristics: [
      'Simple cylindrical bore slightly larger than pipe OD',
      'Secured with fillet welds inside and outside',
      'Lower manufacturing complexity than weld neck',
      'Bore ID is larger than pipe ID for slipping over pipe',
      'Easier alignment during installation',
      'Shorter hub compared to weld neck',
    ],
    pros: [
      'Lower cost than weld neck flanges',
      'Easier and faster installation',
      'Better tolerance for pipe misalignment',
      'Simpler welding (fillet welds only)',
      'Smaller footprint in confined spaces',
      'Available in all standard classes and materials',
    ],
    cons: [
      'Lower stress rating and fatigue life compared to weld neck',
      'Inner diameter fillet weld is stress concentration point',
      'Not suitable for very high pressures or temperatures',
      'Higher vibration and deflection under load',
      'Limited use in critical applications',
      'Bore mismatch can cause turbulence in high-flow services',
    ],
    applications: [
      'Moderate pressure systems (Class 150-600)',
      'Non-critical service piping',
      'Industrial compressed air systems',
      'Building HVAC and water systems',
      'Utility water distribution',
      'Low-temperature applications',
      'General industrial piping (Class 150)',
      'Instrumentation and process control lines',
    ],
    standards: [
      'ASME B16.5 (Classes 150-600, limited higher classes)',
      'EN 1092-1',
      'DIN 2633',
      'JIS B2220',
    ],
    faceOptions: ['Raised Face (RF)', 'Flat Face (FF)', 'Ring Joint (RTJ) - less common'],
  },
  {
    id: 'blind',
    name: 'Blind Flange',
    definition:
      'A blind flange is a solid disc with no center bore. It is used to seal the end of a pipe or nozzle. Unlike other flanges that accommodate pipe passage, a blind flange closes the system completely. They are frequently used on pressure vessel nozzles and as line terminators.',
    characteristics: [
      'Completely solid with no center opening',
      'Essentially a disc bolted to a pipe end',
      'Must support full pressure on internal face',
      'Hub thickness matches other flange types',
      'Concentrates stress in center of disc',
      'Available in all pressure classes and materials',
    ],
    pros: [
      'Simple design with no bore considerations',
      'Versatile - used as end caps and vessel closures',
      'Can be removable (blind flange) or permanent (blind plug)',
      'Easy to install and remove',
      'No bore mismatch issues',
      'Available in all pressure ratings and materials',
    ],
    cons: [
      'High stress concentration in solid center',
      'Requires thicker material for higher pressure classes',
      'Heavier than other flange types of same class',
      'Full pressure acts on center area',
      'Difficult to remove from deep nozzles',
      'Must be properly supported to prevent bending',
    ],
    applications: [
      'Pressure vessel end closures',
      'Vessel nozzle blind-offs',
      'Pipeline end caps and temporary closures',
      'Thermal expansion chambers',
      'Testing caps for line validation',
      'Dead legs and drain connections',
      'Orifice flange carriers (backing flanges)',
      'Permanent system terminators',
    ],
    standards: [
      'ASME B16.5 (Classes 150-2500)',
      'ASME Section VIII (pressure vessels)',
      'ASME B16.47 Series A & B',
      'API 6A, API 6D',
    ],
    faceOptions: ['Raised Face (RF)', 'Flat Face (FF)'],
  },
  {
    id: 'threaded',
    name: 'Threaded Flange',
    definition:
      'A threaded flange has internal threads sized to match the pipe thread. The flange is screwed onto the pipe using the threaded connection. This type is common in smaller piping systems where welding is not practical or desired, providing a mechanical (non-welded) connection.',
    characteristics: [
      'Internal NPT (National Pipe Thread) or metric threads',
      'Mechanical connection - no welding required',
      'Available in small and medium sizes (up to 4" typically)',
      'Female threaded bore matches pipe thread',
      'Hub size optimized for threaded connection',
      'Simple installation by hand or with pipe wrench',
    ],
    pros: [
      'No welding required - field-installable',
      'Easy connection and disconnection for maintenance',
      'Excellent for small diameter piping',
      'No special skills needed for installation',
      'Lower equipment cost (no welding equipment needed)',
      'Suitable for test systems and temporary installations',
    ],
    cons: [
      'Limited to lower pressure classes (typically Class 150-300)',
      'Smaller size range available',
      'Thread stress concentration point',
      'Not suitable for high-temperature services',
      'Can develop leaks if threads are damaged',
      'Limited to mechanical fastening loads',
    ],
    applications: [
      'Small bore instrumentation (1/2" to 2")',
      'Laboratory and test piping',
      'Industrial water and air systems',
      'Low-pressure steam condensate systems',
      'Temporary test installations',
      'Process control lines (small diameter)',
      'Building services piping',
      'HVAC system components (small sizes)',
    ],
    standards: [
      'ASME B16.5 (Classes 150-300, limited higher classes)',
      'ISO 6149 (metric thread)',
      'NPT thread per ASME B4.1',
      'BSP thread (British Standard Pipe)',
    ],
    faceOptions: ['Raised Face (RF)', 'Flat Face (FF)'],
  },
  {
    id: 'socket-weld',
    name: 'Socket Weld Flange',
    definition:
      'A socket weld flange has a recessed socket in the bore that accepts the pipe end. The pipe is inserted into the socket and then fillet welded. This design provides a more compact connection than weld neck flanges while still offering good strength through proper socket dimensions.',
    characteristics: [
      'Recessed socket bore for pipe insertion',
      'Pipe inserted to depth stop in socket',
      'Fillet welded around pipe outside the socket',
      'Compact design - shorter hub than weld neck',
      'Available in small to medium sizes',
      'Hub thickness less than weld neck for same class',
    ],
    pros: [
      'More compact than weld neck flanges',
      'Better stress distribution than slip-on',
      'Smaller footprint for confined spaces',
      'Stronger than threaded connections',
      'Suitable for high-temperature services',
      'Good corrosion performance',
    ],
    cons: [
      'Higher cost than slip-on',
      'Requires skilled welders for socket weld',
      'Limited to smaller piping sizes (typically to 4")',
      'Bore mismatch can cause stress concentration',
      'Not ideal for very high pressures',
      'Difficult to align in confined spaces',
    ],
    applications: [
      'High-temperature steam systems (Class 600+)',
      'Thermal power plants',
      'Chemical processing (small bore)',
      'Instrumentation and vent piping',
      'Oil and gas applications (small bore)',
      'Cryogenic transfer lines',
      'Specialty chemical systems',
      'Space-constrained piping',
    ],
    standards: [
      'ASME B16.5 (Classes 150-2500)',
      'ASME B16.11 (forged fittings)',
      'API 6A (small bore)',
      'EN 1092-1',
    ],
    faceOptions: ['Raised Face (RF)', 'Ring Joint (RTJ)'],
  },
  {
    id: 'lap-joint',
    name: 'Lap Joint Flange',
    definition:
      'A lap joint flange consists of two components: the flange itself and a stub end (lap ring). The stub end fits over the pipe and supports the flange, while the flange slides freely over the stub end. The stub end is welded to the pipe, but the flange is not - providing easy flange removal and replacement.',
    characteristics: [
      'Two-piece design: stub end plus flange',
      'Flange slides over stub end without welding',
      'Stub end welded to pipe',
      'Stub end supports the flange load',
      'Flange can be removed without disturbing pipe',
      'Used with loose backing rings or flat lap rings',
    ],
    pros: [
      'Flange is easily removable without cutting pipe',
      'Ideal for frequent maintenance and inspection',
      'Stub end weld is simpler than full flange weld',
      'Cost-effective when frequent flange replacement needed',
      'Same bolt circle as conventional flange',
      'Easy alignment of bolt holes',
    ],
    cons: [
      'Requires stub ends (two-piece system)',
      'Slightly higher cost due to two components',
      'Flange cannot support radial loads as directly',
      'Stub end weld must be done correctly',
      'Flange bore is larger than pipe ID',
      'Limited to lower pressure classes (Class 150-300 typical)',
    ],
    applications: [
      'Tanks and vessels with frequent access requirements',
      'Valve connections requiring periodic maintenance',
      'Temporary test and research systems',
      'Instrumentation lines',
      'Low-pressure steam and condensate systems',
      'Locations requiring regular equipment replacement',
      'Piping where flange is not permanently attached',
      'Educational laboratory setups',
    ],
    standards: [
      'ASME B16.5 (Classes 150-300)',
      'ASME B16.47',
      'EN 1092-1 Type LE',
      'DIN 2500',
    ],
    faceOptions: ['Raised Face (RF)', 'Flat Face (FF)'],
  },
  {
    id: 'reducing',
    name: 'Reducing Flange',
    definition:
      'A reducing flange is used to connect two pipes of different sizes. The flange bore matches the smaller pipe size while the flange face diameter accommodates the larger pipe size. Reducing flanges eliminate the need for a separate reducer fitting between two different size pipes.',
    characteristics: [
      'Bore size smaller than flange ID',
      'Designed for two different pipe sizes',
      'Available as weld neck or slip-on style',
      'Hub offset to accommodate size transition',
      'Reduces material waste compared to separate reducer',
      'Available in all standard pressure classes',
    ],
    pros: [
      'Eliminates separate reducer fitting',
      'Saves space in piping systems',
      'Reduces number of connections',
      'Cost-effective for size transitions',
      'Available in both weld neck and slip-on',
      'Cleaner, more professional appearance',
    ],
    cons: [
      'More expensive than standard flanges',
      'Limited to specific size combinations',
      'More complex manufacturing',
      'Longer lead times for stock availability',
      'Requires careful selection of correct size combination',
      'Flow restrictions at transition in some designs',
    ],
    applications: [
      'Pump discharge piping (reducing pressure drop)',
      'Heat exchanger inlet/outlet sizing',
      'Main header to branch line transitions',
      'Turbine extraction line systems',
      'Process piping with variable flow requirements',
      'Vessel nozzles at different sizes',
      'Large diameter main lines to smaller branch connections',
      'Load balancing in parallel systems',
    ],
    standards: [
      'ASME B16.5 (custom sizes per customer spec)',
      'ASME B16.47 (large diameter)',
      'EN 1092-1 (European sizes)',
      'Custom per engineering requirements',
    ],
    faceOptions: ['Raised Face (RF)', 'Flat Face (FF)'],
  },
  {
    id: 'long-weld-neck',
    name: 'Long Weld Neck Flange (LWN)',
    definition:
      'A long weld neck flange extends the tapered hub significantly longer than standard weld neck flanges. The extended hub provides additional stress relief, better alignment, and enhanced load distribution. LWN flanges are specified for critical applications requiring maximum reliability and longevity.',
    characteristics: [
      'Extended tapered hub (typically 1.5x to 2x standard)',
      'Gradual stress transition over longer distance',
      'Better for thick-wall and high-pressure pipe',
      'Improved alignment characteristics',
      'More material and longer machining required',
      'Maximum stress relief properties',
    ],
    pros: [
      'Superior stress distribution over extended length',
      'Best option for thick-wall piping (schedules 160, XXS)',
      'Excellent for vibration-prone services',
      'Maximum fatigue resistance',
      'Superior corrosion protection at weld',
      'Best choice for critical high-temperature applications',
    ],
    cons: [
      'Highest cost among weld neck variations',
      'Longer lead times for manufacturing',
      'Requires more skilled welding',
      'Extended hub may be problematic in confined spaces',
      'Heavier than standard weld neck',
      'Not always necessary for lower pressure classes',
    ],
    applications: [
      'Supercritical steam systems (ASME Class 1300-2500)',
      'Nuclear reactor cooling systems',
      'Ultra-high-temperature processing',
      'Thick-wall cryogenic systems',
      'Critical pressure vessels',
      'Extreme service petrochemical applications',
      'Subsea deep-water piping',
      'Research reactor and experimental systems',
    ],
    standards: [
      'ASME B16.5 (all classes, specified as LWN option)',
      'ASME B16.47 (large diameter LWN)',
      'MSS SP-44 (weld neck flange dimensions)',
      'API 6A (wellhead equipment)',
    ],
    faceOptions: ['Raised Face (RF)', 'Ring Joint (RTJ)', 'Flat Face (FF)'],
  },
  {
    id: 'orifice',
    name: 'Orifice Flange',
    definition:
      'Orifice flanges are specialized flanges used to mount orifice plates for flow measurement. The flange pair includes pressure tap holes designed to connect differential pressure transmitters. An orifice flange pair is bolted on either side of an orifice plate, with the plate captured between them.',
    characteristics: [
      'Two-piece system (upstream and downstream flanges)',
      'Precision-machined pressure tap holes',
      'Standard tap positions (vena contracta, D, 1D/2D)',
      'Integral or separate orifice plate carrier',
      'Designed for accurate flow calculation',
      'Available in all pressure classes',
    ],
    pros: [
      'Dedicated design for flow measurement accuracy',
      'Standard tap configurations per ASME and ISO',
      'Reduces connection hardware',
      'Precision tapping ensures measurement accuracy',
      'Cost-effective for permanent flow monitoring',
      'Easy pressure transmitter connection',
    ],
    cons: [
      'Pressure drop across orifice plate (energy loss)',
      'Requires careful flange alignment for accuracy',
      'Not suitable for highly viscous or slurry services',
      'Restricted to standard orifice plate sizes',
      'Higher cost than conventional flanges',
      'Tap plugging risk with dirty fluids',
    ],
    applications: [
      'Process fluid flow measurement and control',
      'Natural gas metering stations',
      'Steam flow measurement (power plants)',
      'Hydrocarbon and chemical flow monitoring',
      'HVAC system balancing',
      'Water distribution systems',
      'Oil and gas pipeline measurement',
      'Custody transfer applications',
    ],
    standards: [
      'ASME B16.5 with B16.36 (orifice plates)',
      'ASME MFC-3M (orifice flow measurement)',
      'ISO 5167 (orifice plates)',
      'AGA Report No. 3 (natural gas)',
    ],
    faceOptions: ['Raised Face (RF)', 'Flat Face (FF)'],
  },
  {
    id: 'spectacle-blind',
    name: 'Spectacle Blind (Isolation Plate)',
    definition:
      'A spectacle blind (also called a spectacle flange or isolation plate) consists of two circular discs connected by a bar or bridge, resembling eyeglasses (spectacles). One disc is solid (blind) to isolate/block flow, while the other is open with a bore. Both are bolted to flanges. By rotating 180 degrees, the operator can switch between isolation and flow states without breaking the connection.',
    characteristics: [
      'Two-disc assembly: solid disc and ring with bore',
      'Connected by rigid bar (bridge)',
      'Rotates 180 degrees between isolation and flow',
      'Ring spacer alternative (two separate plates)',
      'Requires proper bolt torque to seat effectively',
      'Available in all pressure classes and materials',
    ],
    pros: [
      'No line breakage required to switch between isolation and flow',
      'Less expensive than isolation ball valve',
      'Visual indication of position (disc orientation)',
      'Versatile - can be inserted or removed with line live',
      'Works for any fluid type (no mechanical seals)',
      'Available for high-pressure and high-temperature service',
    ],
    cons: [
      'Requires depressurization to rotate safely',
      'Requires bolts to be unbolted to rotate (some designs)',
      'Potential for human error in positioning',
      'Does not provide emergency isolation (unlike block valve)',
      'Prone to operator mistakes',
      'Requires clear marking and training',
    ],
    applications: [
      'Isolation during maintenance and turnarounds',
      'Pump bypass loops (pad ring configuration)',
      'Thermal expansion relief systems (paddle blind)',
      'Low-cost isolation instead of block valves',
      'Test piping and temporary systems',
      'Slurry and viscous service (where valves problematic)',
      'Instrumentation isolation',
      'Piping section isolation between plant units',
    ],
    standards: [
      'ASME B16.5 (flange component)',
      'API 6A (wellhead spectacle blinds)',
      'ASME Section VIII (pressure vessel nozzles)',
      'Manufacturer-specific designs per application',
    ],
    faceOptions: ['Raised Face (RF)', 'Flat Face (FF)'],
  },
  {
    id: 'plate',
    name: 'Plate Flange',
    definition:
      'Plate flanges are manufactured from steel plate by flame cutting, rolling, and welding, rather than forging. They are used in larger diameter applications (typically 24" and above) where forged flanges become impractical or prohibitively expensive. Plate flanges are built-up designs welded to form the flange structure.',
    characteristics: [
      'Fabricated from steel plate stock',
      'Welded construction (hub to flat ring)',
      'Used for large diameter piping (24"+)',
      'Lower manufacturing cost than forging for large sizes',
      'Less stringent material control than forgings',
      'Available in weld neck and slip-on configurations',
    ],
    pros: [
      'Cost-effective for large diameter services',
      'Shorter lead times for standard sizes',
      'Can be customized to specific project requirements',
      'Available for both standard and non-standard sizes',
      'Lighter per unit strength compared to forgings',
      'Easier to store and transport large sizes',
    ],
    cons: [
      'Lower quality material control compared to forgings',
      'Welding adds risk of defects and lamellar tearing',
      'Less fatigue resistance in high-vibration services',
      'May require post-weld heat treatment',
      'Potential for segregation in thicker sections',
      'May not be acceptable for critical or ASME Section I applications',
    ],
    applications: [
      'Large diameter water main systems (24" to 60"+)',
      'Power plant circulating water systems',
      'District heating/cooling piping',
      'Industrial waste systems',
      'Process piping for low-pressure services',
      'Industrial utility piping',
      'Municipal water distribution (Class 150-300)',
      'Non-critical industrial applications',
    ],
    standards: [
      'AWWA C207 (steel plate flanges for water)',
      'ASME B16.5 (limited applications)',
      'API 605 (petrochemical)',
      'Custom per ASME Section VIII (if pressure vessel)',
    ],
    faceOptions: ['Raised Face (RF)', 'Flat Face (FF)'],
  },
  {
    id: 'backing-ring',
    name: 'Backing Ring (Backup Ring)',
    definition:
      'A backing ring (also called a backup ring) is a temporary ring placed behind a flange weld to support the weld metal and prevent the weld from falling through the pipe bore. The backing ring is permanently left in place after welding and becomes part of the finished connection. It is primarily used with slip-on flanges.',
    characteristics: [
      'Ring-shaped insert placed behind flange weld',
      'Supports molten weld metal during fillet welding',
      'Becomes permanent part of the connection',
      'Available in carbon steel, stainless, and alloys',
      'Sized to fit pipe ID with small clearance',
      'Used to improve weld quality and repeatability',
    ],
    pros: [
      'Improves weld quality and repeatability',
      'Prevents weld metal from falling into pipe',
      'Ensures full penetration inside diameter',
      'Reduces welder skill level requirement',
      'Provides consistent weld profile',
      'Cost-effective way to improve weld reliability',
    ],
    cons: [
      'Adds material cost to connection',
      'Permanent installation (cannot be easily removed)',
      'Can cause erosion/corrosion if flow sensitive',
      'Foreign object risk if not properly secured',
      'Adds to total connection cost',
      'Requires proper sizing for pipe specifications',
    ],
    applications: [
      'Slip-on flange welds (very common)',
      'Low-pressure carbon steel piping',
      'Repeated connections where consistency critical',
      'Training systems where weld repeatability important',
      'Non-critical piping where cost-savings matter',
      'Backing for socket weld flanges',
      'Industrial process piping (non-critical)',
      'Utility piping systems',
    ],
    standards: [
      'ASME B16.5 (backup ring material and specifications)',
      'AWS D1.1 (welding specifications)',
      'AWWA C207 (for water systems)',
      'Customer-specific welding procedures',
    ],
    faceOptions: ['N/A - Ring only, not a complete flange'],
  },
  {
    id: 'exhaust',
    name: 'Exhaust Flange',
    definition:
      'An exhaust flange is specialized for high-temperature exhaust gas applications such as turbine exhausts, engine exhaust systems, and boiler flue gas outlets. These flanges handle extreme temperatures (often 500-1200°F+) with minimal pressure while accommodating thermal expansion and vibration from gas flow.',
    characteristics: [
      'Designed for high temperatures with low pressure',
      'Often asymmetrical design for exhaust flow patterns',
      'Cast or forged in high-temperature alloys',
      'Larger bore than pressure-rated flanges (same nominal size)',
      'Accommodates thermal expansion of exhaust piping',
      'May have special drilling for thermal movement',
    ],
    pros: [
      'Optimized for thermal cycling and vibration',
      'Better suited to pulsating exhaust flows',
      'Less restrictive to flow (larger bore)',
      'Can use lower pressure class ratings',
      'Cost-effective for low-pressure high-temp service',
      'Good fatigue resistance under cycling conditions',
    ],
    cons: [
      'Limited to low-pressure applications',
      'Not suitable for high-pressure systems',
      'Material selection critical for temperature',
      'Thermal expansion requires proper design',
      'Special gasket selection required',
      'Cannot be substituted with pressure-rated flanges',
    ],
    applications: [
      'Steam turbine exhaust connections',
      'Industrial boiler flue gas piping',
      'Engine exhaust manifold assemblies',
      'Thermal power plant turbine exhausts',
      'Waste heat recovery systems',
      'Furnace exhaust ducting (low pressure)',
      'Incinerator outlet piping',
      'Industrial kiln and dryer exhaust',
    ],
    standards: [
      'ASME B16.36 (exhaust flanges)',
      'API 612 (steam turbines)',
      'Customer-specific designs',
      'Material specifications per design pressure and temperature',
    ],
    faceOptions: ['Custom per application - often flat face'],
  },
  {
    id: 'hub',
    name: 'Hub Flange (Stub End Assembly)',
    definition:
      'A hub flange is essentially the stub end component of a lap joint assembly, designed to support a separate flange. The hub features a welded connection to the pipe and a flat surface for the flange to rest upon. Hub flanges are used in applications requiring frequent disassembly while maintaining structural integrity.',
    characteristics: [
      'One-piece hub and ring assembly',
      'Welded to pipe permanently',
      'Supports a sliding flange on top',
      'Available in weld neck, slip-on, and threaded styles',
      'Designed for lap joint applications',
      'Bore size matches pipe ID',
    ],
    pros: [
      'Simplifies maintenance by allowing flange removal',
      'Strong permanent connection to pipe',
      'Flange can be replaced without pipe modification',
      'Good stress distribution from hub design',
      'Versatile for custom applications',
      'Economical for frequent access points',
    ],
    cons: [
      'Requires two-piece design (hub plus flange)',
      'More complex than single-piece flanges',
      'Hub weld is critical to connection integrity',
      'Flange cannot directly support loads',
      'More components than conventional flanges',
      'Not suitable for all pressure classes',
    ],
    applications: [
      'Pressure vessel nozzles requiring access',
      'Pump and motor connections',
      'Cooler and heat exchanger connections',
      'Tank inlet and outlet connections',
      'Instrumentation isolation valves',
      'Branch connections to main headers',
      'Temporary or test system connections',
      'Equipment removal and replacement',
    ],
    standards: [
      'ASME B16.5 (lap joint flange component)',
      'ASME B16.47 (large diameter)',
      'ASME Section VIII (pressure vessels)',
      'Customer specifications',
    ],
    faceOptions: ['Raised Face (RF)', 'Flat Face (FF)'],
  },
  {
    id: 'swivel-ring',
    name: 'Swivel Ring Flange',
    definition:
      'A swivel ring flange features a rotating ring that can be adjusted 360 degrees without unbolting the connection. The ring rotates freely on the flange hub, allowing alignment adjustment without disturbing the bolt circle. This specialized design is used in applications requiring frequent or precision alignment adjustments.',
    characteristics: [
      'Ring rotates freely on hub bushing',
      'No bolts need to be removed for rotation',
      'Bearing surface allows smooth rotation',
      'Maintains bolt hole alignment while ring rotates',
      'Available in weld neck and slip-on designs',
      'Typically used in smaller size ranges',
    ],
    pros: [
      'Easy 360-degree alignment adjustment',
      'No bolts need to be disturbed',
      'Reduces assembly time and errors',
      'Allows fine-tuning of connection alignment',
      'Useful in confined spaces with alignment challenges',
      'Improves connection repeatability',
    ],
    cons: [
      'More expensive than standard flanges',
      'Limited to smaller sizes',
      'Rotating ring must be secured after adjustment',
      'Bushing can wear under heavy vibration',
      'Not suitable for high-vibration services',
      'More complex manufacturing',
    ],
    applications: [
      'Precision instrumentation connections',
      'Research and laboratory piping',
      'Optical and analytical equipment connections',
      'Aerospace component connections',
      'Space-constrained alignment requirements',
      'Calibration systems',
      'Test fixture piping',
      'Equipment mock-ups during development',
    ],
    standards: [
      'ASME B16.5 (as optional feature)',
      'Customer-specific engineering requirements',
      'Military specifications (MIL-STD) for some applications',
      'Aerospace standards (AS, NAS) for specialized uses',
    ],
    faceOptions: ['Raised Face (RF)', 'Flat Face (FF)'],
  },
];

const tableOfContents: TOCItem[] = [
  { id: 'introduction', title: 'Introduction', level: 1 },
  { id: 'weld-neck', title: 'Weld Neck Flange', level: 2 },
  { id: 'slip-on', title: 'Slip-On Flange', level: 2 },
  { id: 'blind', title: 'Blind Flange', level: 2 },
  { id: 'threaded', title: 'Threaded Flange', level: 2 },
  { id: 'socket-weld', title: 'Socket Weld Flange', level: 2 },
  { id: 'lap-joint', title: 'Lap Joint Flange', level: 2 },
  { id: 'reducing', title: 'Reducing Flange', level: 2 },
  { id: 'long-weld-neck', title: 'Long Weld Neck Flange', level: 2 },
  { id: 'orifice', title: 'Orifice Flange', level: 2 },
  { id: 'spectacle-blind', title: 'Spectacle Blind', level: 2 },
  { id: 'plate', title: 'Plate Flange', level: 2 },
  { id: 'backing-ring', title: 'Backing Ring', level: 2 },
  { id: 'exhaust', title: 'Exhaust Flange', level: 2 },
  { id: 'hub', title: 'Hub Flange', level: 2 },
  { id: 'swivel-ring', title: 'Swivel Ring Flange', level: 2 },
  { id: 'comparison', title: 'Flange Type Comparison Table', level: 1 },
  { id: 'decision-tree', title: 'Flange Selection Decision Tree', level: 1 },
  { id: 'faq', title: 'Frequently Asked Questions', level: 1 },
];

export default function FlangeTypesGuidePage() {
  return (
    <>
      <PageHero
        title="The Complete Flange Types Guide"
        subtitle="Master all 15 flange types with detailed specifications, applications, and selection criteria. 4000+ words of comprehensive technical content."
        variant="navy"
      />
      <FlangeTypesGuideClient />
    </>
  );
}
